Feature/handle game
inna-svn/Checkers pull request #1
Opened 2022-08-02 21:04 UTC by meiravanidjar

2022-08-03 08:05 UTC, ilyash-b commented on src/main/java/CheckersGame.java
> +        Map<Piece, List<Move>> currMap = new HashMap();
Should be `new HashMap<>()`

2022-08-03 08:06 UTC, ilyash-b commented on src/main/java/CheckersGame.java
> +        if (move.intermediates() != null) { this.board.setPiece(move.intermediates(), null); }
`setPiece(..., null)` should be `removePiece(...)`

2022-08-03 08:16 UTC, ilyash-b commented on src/main/java/Location.java
> +    public int getY() { return this.y; }
Java record provides getters. Please don't add these.

2022-08-03 08:18 UTC, ilyash-b commented on src/main/java/Move.java
> +public record Move(Location start, Location end, Location intermediates) { }
`intermediates` supposed to hole multiple intermediate locations, not single

2022-08-03 08:26 UTC, ilyash-b commented on src/main/java/CheckersGame.java
> +                board.setPiece(currLocation, new CheckersPiece(board, currColor, currLocation));
I recommend that `CheckersPiece` constructor would place the piece on the board instead of `board.setPiece()` here.

2022-08-03 08:31 UTC, ilyash-b commented on src/main/java/CheckersGame.java
> +        this.board.setPiece(move.end(), this.board.getPiece(move.start()));
Todo: remove opponent's pieces when appropriate

2022-08-03 08:33 UTC, ilyash-b commented on src/main/java/CheckersKingPiece.java
> +        else { return false; }
Please replace all `if(COND) { return true; } else { return false; }` with `return COND`.

2022-08-03 08:35 UTC, ilyash-b commented on src/main/java/CheckersKingPiece.java
> +        List<Move> moves = new ArrayList<Move>();
Bug: `moves` is never read from. (My IDE spotted this)

2022-08-03 08:37 UTC, ilyash-b commented on src/main/java/CheckersKingPiece.java
>      public List<Move> listPossibleMoves() {
I would expect `listPossibleMoves()` to have a recursion somewhere but it doesn't. Looks like multi-step moves are completely ignored.

2022-08-03 08:41 UTC, ilyash-b commented on src/main/java/Move.java
> +public record Move(Location start, Location end, Location intermediates) { }
It also looks like `intermediates` are used for the captured piece of the oponent.
* `intermediates` were intended for intermediate steps of this piece, not for captured pieces
* In both cases, it's multiple, not one

2022-08-03 08:42 UTC, ilyash-b commented on src/main/java/CheckersKingPiece.java
> +    private boolean isNextCellEmpty(int directionX, int directionY){
Is there any check for being on the board or outside of the board?

2022-08-03 08:49 UTC, ilyash-b commented on src/main/java/CheckersPiece.java
> +        return moves;
Hard to follow.
Maybe introduce `Direction` and/or other abstractions?
`Location` with `Direction` could give new `Location`, etc.

2022-08-03 08:50 UTC, ilyash-b requested changes
Finished preliminary round. Main issue: missing handling of multi-step moves.

2022-08-03 09:28 UTC, meiravanidjar commented on src/main/java/CheckersKingPiece.java
>      public List<Move> listPossibleMoves() {
correct ,I wanted to discuss with you about option to have only single capture ,to eliminate the recursion here ,and this is why also I replaced intermidiates from list to single location .what do you think ?is it critical to have multi-capture moves ?

2022-08-04 09:30 UTC, ilyash-b commented on src/main/java/CheckersKingPiece.java
>      public List<Move> listPossibleMoves() {
> is it critical to have multi-capture moves ?

Not a pro gamer but whenever I played, multi-capture moves were always there.

2022-08-06 08:25 UTC, ilyash-b commented
@meiravanidjar , let me know if anything is unclear, we can schedule a meeting

2022-08-06 15:36 UTC, meiravanidjar commented on src/main/java/CheckersPiece.java
> +        return moves;
@ilyash-b lets talk about this one.
can we schedule meeting for tomorrow?

2022-08-08 09:26 UTC, ilyash-b commented on src/main/java/CheckersPiece.java
> +        return moves;
Sorry, had crazy day. Let's be in touch today to schedule (using private channels)

2022-08-09 19:12 UTC, merged