added my score page
inna-svn/Checkers pull request #17
Opened 2022-09-15 14:26 UTC by meiravanidjar

2022-09-16 07:09 UTC, ilyash-b requested changes

2022-09-16 07:09 UTC, ilyash-b commented on src/main/java/UserSession.java
> +    private UserGameScore score;
Can't be here. It's per game, not per user.

2022-09-16 07:09 UTC, ilyash-b commented on src/main/java/UserSession.java
> +
Can't work like this. It's not a property of the user. It's per game.

2022-09-16 07:09 UTC, ilyash-b commented on src/main/webapp/home.xhtml
> +                    <p:commandLink value="#{lobby.gameName}- My Scores " action="#{userSession.scoreForGame(lobby.gameClass)}" oncomplete="window.open('scores.xhtml')"/>
Please don't set property on User just to fetch it later. Use the function that you need, wherever you need to fetch the data that you want.

2022-09-16 07:09 UTC, ilyash-b commented on src/main/webapp/scores.xhtml
> +        </div>
This should all be per game. There should be a loop over all supported games, right now it's only Checkers.

2022-09-17 06:44 UTC, ilyash-b commented on src/main/webapp/home.xhtml
> +                    <p:commandLink value="#{lobby.gameName}- My Scores " action="#{userSession.scoreForGame(lobby.gameClass)}" oncomplete="window.open('scores.xhtml')"/>
How `p:commandLink` is different from `h:commandLink`?

2022-09-17 13:30 UTC, meiravanidjar commented on src/main/webapp/home.xhtml
> +                    <p:commandLink value="#{lobby.gameName}- My Scores " action="#{userSession.scoreForGame(lobby.gameClass)}" oncomplete="window.open('scores.xhtml')"/>
p is for using primefaces dependency (I used this for using the oncomplete=window.open )

2022-09-17 13:32 UTC, meiravanidjar commented on src/main/java/UserSession.java
> +    private UserGameScore score;
ok , please review again
I removed the score from here ,and used the return value directly from the function (inside loop over the game classes)

2022-09-18 10:17 UTC, merged