database
inna-svn/Checkers pull request #9
Opened 2022-08-31 20:44 UTC by inna-svn

Changed userSession, added database web driver, changed sql dump file

2022-09-01 13:18 UTC, ilyash-b commented on MySQL____localhost-2022_08_30-dump.sql
> +  PRIMARY KEY (`id`,`name`)
Should be just ```(`id`)```

2022-09-01 13:19 UTC, ilyash-b commented on MySQL____localhost-2022_08_30-dump.sql
> +  `password` varchar(50) DEFAULT NULL,
Nope, we can't have users without `userName` or `password`. Should stay `NOT NULL`.

2022-09-01 13:23 UTC, ilyash-b commented on src/main/java/Main.java
> +        List<Move> moves = currMapp.get(g.getBoard().getPiece(new Location(0, 1)));
Should all be moving into tests, as @meiravanidjar does

2022-09-01 15:34 UTC, ilyash-b commented on src/main/java/User.java
> +            return signIn(newUser, password);
I don't think we should be signing in the user here. We already have the User object and there is no additional functionality in User#signIn method.

2022-09-01 15:38 UTC, ilyash-b reviewed
See comments

2022-09-03 11:06 UTC, inna-svn commented
Please see my last commit

2022-09-04 18:26 UTC, ilyash-b commented on src/main/java/Database.java
> +            }
What happens if this code is removed?

2022-09-04 18:31 UTC, ilyash-b commented on src/main/java/Database.java
> +    public void createNewUserInDB(String username, String password) throws User.SignUpError {
Please rename `createNewUserInDB` -> `createUser`

* `create` implies `new`
* `InDB` is also clear because it's `Database` class

2022-09-04 18:33 UTC, ilyash-b commented on src/main/java/Database.java
> +    public void createNewUserInDB(String username, String password) throws User.SignUpError {
It also makes sense that this method would return either the newly created `User` or at least id of the user generated by the database.

2022-09-04 18:38 UTC, ilyash-b commented on src/main/java/Database.java
> +            preparedStmt.executeUpdate();
Is `preparedStmt.executeUpdate();` needed here? There is `reparedStmt.executeQuery();` just below ...

2022-09-04 18:40 UTC, ilyash-b commented on src/main/java/Database.java
> +        String saveRate = "UPDATE scores SET rate = ? WHERE userId = ? ";
As discussed, rates are per user+game

2022-09-04 18:41 UTC, ilyash-b commented on src/main/java/Main.java
> +        User existingUser = null;
Please move all test to test files

2022-09-04 18:45 UTC, ilyash-b commented on src/main/java/User.java
> +    static void signUp(@NotNull String username, @NotNull String password) throws SignUpError {
Should return `User`, as previously

2022-09-04 18:46 UTC, ilyash-b requested changes
See comments

2022-09-07 07:13 UTC, inna-svn commented on src/main/java/Database.java
> +        String saveRate = "UPDATE scores SET rate = ? WHERE userId = ? ";
to discuss: how we get game type

2022-09-07 07:16 UTC, inna-svn commented on src/main/java/User.java
> +    static void signUp(@NotNull String username, @NotNull String password) throws SignUpError {
to discuss: signIn returns User, why signUp need to return it? 
user can singUp & signIn & signOut and then reconnect as existing user.

2022-09-10 14:51 UTC, inna-svn commented
@ilyash-b please review

2022-09-10 16:30 UTC, ilyash-b approved these changes

2022-09-10 16:30 UTC, merged